### ISSUE TITLE
Debezium support

### ISSUE THREAD

**Issue by jsalmeron** [blueapron/kafka-connect-protobuf-converter#14]
Hello; I'm really interested in your serde class

However, in having to specify a proto class in the connector, I am left at odds as what to provide; surely, anything I configure for value.converter.protoClassName fails with

`[2019-01-31 19:45:18,288] ERROR Failed to start task blueapron-protos-source-0 (org.apache.kafka.connect.runtime.Worker:455)
java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException
	at com.blueapron.connect.protobuf.ProtobufConverter.configure(ProtobufConverter.java:43)
	at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:266)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:422)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.createConnectorTasks(StandaloneHerder.java:315)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.updateConnectorTasks(StandaloneHerder.java:340)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:211)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:107)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.InvalidProtocolBufferException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 7 more`

What would be the idea here, creating a generic proto for debezium?

**Comment by sschatts** [comment]
Closing due to no response. Please reopen if you have more questions.

**Comment by linxd** [comment]
2022-07-04 17:26:53,043 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.ClassNotFoundException: io.confluent.connect.protobuf.ProtobufConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.debezium.config.Instantiator.getInstanceWithProvidedConstructorType(Instantiator.java:50)
        at io.debezium.config.Instantiator.getInstance(Instantiator.java:28)
