### ISSUE TITLE
org.apache.kafka.connect.errors.DataException

### ISSUE THREAD

**Issue by arazmj** [blueapron/kafka-connect-protobuf-converter#19]
I am trying to sink Int32Values from my Kafka topic into Cassandra using the following configuration:
`
{
  "connector.class": "com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector",
  "connect.cassandra.key.space": "tutorialspoint",
  "connect.cassandra.contact.points": "cassandra",
  "topics": "ii",
  "tasks.max": "1",
  "connect.cassandra.kcql": "INSERT INTO names SELECT * FROM ii",
  "connect.cassandra.port": "9042",
  "name": "CassandraSinkConnector2",
  "value.converter": "com.blueapron.connect.protobuf.ProtobufConverter",
  "value.converter.protoClassName": "com.google.protobuf.Int32Value",
  "connect.cassandra.password": "cassandra",
  "connect.cassandra.username": "cassandra"
}
`

 I put the protobuf class and kafka-connect-protobuf-converter in the CLASSPATH.
I receive the following error.
`
org.apache.kafka.connect.errors.DataException: ii
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:97)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:406)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:361)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:120)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:194)
	at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:121)
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:85)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:406)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by sschatts** [comment]
@arazmj Looks like you are missing the line following line in your configuration:
`"key.converter": "com.blueapron.connect.protobuf.ProtobufConverter"`
See the [usage documentation](https://github.com/blueapron/kafka-connect-protobuf-converter/blob/master/README.md#usage), it mentions three specific converter parameters.

**Comment by arazmj** [comment]
My key is a simple integer. Do I still need to specify `key.converter'. This is the Java code for the producer. 
```Java
  int messageNo = 1;
        while (true) {
            Int32Value int32Value = Int32Value.newBuilder()
                    .setValue(messageNo)
                    .build();
            try {
                producer.send(new ProducerRecord<>(topic,
                        messageNo,
                        int32Value)).get();
                System.out.println("Sent message: ("+ int32Value + ")");
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
            }
            ++messageNo;
        }
```

**Comment by bayardneville** [comment]
Did you try specifying `"key.converter": "com.blueapron.connect.protobuf.ProtobufConverter"? Your error suggests that the avro converter is being used instead of the protobuf converter.

**Comment by mike9005** [comment]
Closing this issue as inactive - please re-open if you're still seeing this error.
