### ISSUE TITLE
JDBC Sink Connector: Unsupported source data type: STRUCT

### ISSUE THREAD

**Issue by bilocan** [blueapron/kafka-connect-protobuf-converter#58]
Hi,
I have extended the converter for complex protobuf types. Jdbc source connector works perfectly and now i am working on jdbc sink connector. I have a topic with protobuf scheme, which has nested types. I am getting following exception:
```
org.apache.kafka.connect.errors.ConnectException: Unsupported source data type: STRUCT
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.bindField(GenericDatabaseDialect.java:1569)
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindField(PreparedStatementBinder.java:149)
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindNonKeyFields(PreparedStatementBinder.java:143)
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindRecord(PreparedStatementBinder.java:78)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:182)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:79)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:326)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```
I have compared my SchemaAndValue returned from method toConnectData(byte[] value) with test examples and they look similar.
I am not sure if this is a connect issue or converter issue.
Best,
Bilal

**Comment by nicownano** [comment]
Did you solve it ?

**Comment by bilocan** [comment]
yes i have implemented own converter kafka-connect-protobuf-converter) and used it in the connector
