### ISSUE TITLE
Can I use the converter with a complex message of different Protobuf types

### ISSUE THREAD

**Issue by AhmadEldefrawy** [blueapron/kafka-connect-protobuf-converter#6]
Hello Megan,

I am interested in using this converter with a complex message that has multiple Protobuf types.
Can I use `value.converter.protoClassName` with my own class definition of a message.
 
My Model.proto files looks something like this:
```
message Envelope {
    required bytes event_id = 1;
    optional int32 sub_event_id = 2;
    optional string event_key = 3;
    optional bytes remote_address = 4;
    optional int64 event_time = 5;
    optional int64 server_time = 6;
    required string test_id = 8;
    optional string data_schema_url = 9;
}
```

Thank you in advance. And special thanks for sharing the converter.

**Comment by AhmadEldefrawy** [comment]
Thank you for your reply.

So I compiled my `.proto` files with `protoc` and packaged them in a Jar. I added this model Jar with the converter Jar to some directory which I added to environment `CLASSPATH`.

But I still have this error:
```
java.lang.NoClassDefFoundError: Could not initialize class com.advertine.deep.model.DeepModel
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.blueapron.connect.protobuf.ProtobufConverter.configure(ProtobufConverter.java:43)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:326)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:834)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1500(DistributedHerder.java:101)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:848)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:844)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I am using it with Kafka `0.10.2` and Confluent `3.2.0`.
Any ideas what I might be doing wrong here ?

**Comment by makearl** [comment]
I'd take a look at your compiled Java file to check what the class is, but here's the pattern we've seen:

When a proto message is in a file that has the same name as the message, for example the message `MyMessage` is in `MyMessage.proto`, the proto will be referenced by `my.java.package.MyMessageOuterClass$MyMessage`

When a proto message is in a file that does not have the same name as the message, the Java class will be `my.java.package.MyFile$MyMessage`

**Comment by AhmadEldefrawy** [comment]
I have the name of the message different than the file. Your recommendation actually solved this error for me.

But I'm not still quite out of the woods:
```
java.lang.NoClassDefFoundError: Could not initialize class com.advertine.deep.model.DeepModel
	at com.advertine.deep.model.DeepModel$DeepEnvelope.internalGetFieldAccessorTable(DeepModel.java:377)
	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:110)
	at com.blueapron.connect.protobuf.ProtobufData.toConnectSchema(ProtobufData.java:113)
	at com.blueapron.connect.protobuf.ProtobufData.<init>(ProtobufData.java:99)
	at com.blueapron.connect.protobuf.ProtobufConverter.configure(ProtobufConverter.java:43)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:326)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:834)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1500(DistributedHerder.java:101)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:848)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:844)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by makearl** [comment]
I haven't seen that error before, but I'm wondering if it's related to the proto version. Are you using v2 or v3 proto syntax? Right now, the converter is set up to use v3

**Comment by makearl** [comment]
Is it possible to post your proto file to provide more info?
